// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeVi5mtkWFt6GaaotwhaSzXOcToF749ko',
    appId: '1:1090870808559:web:82e217a31125265b08701a',
    messagingSenderId: '1090870808559',
    projectId: 'flutter-application-91c47',
    authDomain: 'flutter-application-91c47.firebaseapp.com',
    storageBucket: 'flutter-application-91c47.appspot.com',
    measurementId: 'G-WG7XNPLPLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa61VbfNlKfMMRob44Du_hlFfKWFS4EUk',
    appId: '1:1090870808559:android:bae308d35205770608701a',
    messagingSenderId: '1090870808559',
    projectId: 'flutter-application-91c47',
    storageBucket: 'flutter-application-91c47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqFg19lNi7v-whRchS233WrBHTAC7aqvQ',
    appId: '1:1090870808559:ios:9fb15fabd6995bc608701a',
    messagingSenderId: '1090870808559',
    projectId: 'flutter-application-91c47',
    storageBucket: 'flutter-application-91c47.appspot.com',
    iosBundleId: 'com.example.xteamProApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqFg19lNi7v-whRchS233WrBHTAC7aqvQ',
    appId: '1:1090870808559:ios:9fb15fabd6995bc608701a',
    messagingSenderId: '1090870808559',
    projectId: 'flutter-application-91c47',
    storageBucket: 'flutter-application-91c47.appspot.com',
    iosBundleId: 'com.example.xteamProApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeVi5mtkWFt6GaaotwhaSzXOcToF749ko',
    appId: '1:1090870808559:web:29ddfe43975e9e4108701a',
    messagingSenderId: '1090870808559',
    projectId: 'flutter-application-91c47',
    authDomain: 'flutter-application-91c47.firebaseapp.com',
    storageBucket: 'flutter-application-91c47.appspot.com',
    measurementId: 'G-QKZ7ZBE6Q9',
  );
}
